spring:
    config:
      activate:
          on-profile: test
    datasource:
        url:  jdbc:h2:mem:jcDb
        username : root
        password : root
        driver-class-name: org.h2.Driver
    flyway:
        enabled: false
    jpa:
        show-sql: true
        database-platform: org.hibernate.dialect.H2Dialect

